### ISSUE TITLE
Panic if the game isn’t running

### ISSUE THREAD

**Issue by ticky** [etra0/yakuza-freecam#1]
Without any info on how to use this (though I added some in #2!), I tried running the exe, and it failed with a panic message, and ultimately it was only reading the source code that revealed that the panic was because it expected the game to be running already:

```
thread 'main' panicked at 'assertion failed: process_id != 0', memory-rs\src\process\mod.rs:46:5
```

It’d be nice if the program would explain that the process needs to be running first, rather than this panic about a process ID being zero:

https://github.com/etra0/memory-rs/blob/c3653691f296e08d562985f897428b48dddde93d/src/process/mod.rs#L46

I’d be willing to help out but given it requires a patch to both this _and_ your `memory-rs` to return `Error` types rather than panic I didn’t want to jump right in presumptuously! Let me know if you’d like me to tackle that.

**Comment by etra0** [comment]
Oh, please feel free to contribute!

I'm new in Rust so I do not know how to handle panics properly, so any help is welcome!

This is the project I chosed to learn this language, so your contribution will probably help in my learning too.

**Comment by ticky** [comment]
Awesome. Just wanted to check I wouldn’t be stepping on any toes if I opened some PRs.

I’ve got a bit of Rust experience but I’ve not done much directly with the Windows API, but I think I can see a nice path forward for this! ☺️
