### ISSUE TITLE
More camera controls?

### ISSUE THREAD

**Issue by curagea** [etra0/yakuza-freecam#7]
Hello!

I've been enjoying your freecam tool; it's a lot of fun! I'm wondering if it's possible to add a few more directional controls for the camera.

I'm looking for strafe-up and strafe-down movement (so basically "jump" and "crouch" directions if that makes any sense). Currently in order to move the camera up or down, I have to first look up/down then press forward or backward.

The following are totally optional, no worries if they aren't possible:

- rotating the camera clockwise and counterclockwise would be cool,
- ~~Changing the FoV. Especially during cutscenes with a far FoV, it's tough to get closeups of characters without clipping into their models.~~ Sorry I'm an idiot, I just noticed the FoV controls >.<

(Sorry, I'm totally spoiled by NVidia Ansel ^_^;;;)

Thanks for your efforts! It's an awesome tool!
-- Curagea

**Comment by etra0** [comment]
I have plans on implementing the strafe-up strafe-down movement, I'll do it as soon as I clean up the code, because right now there's too much redundancy so I want to avoid writing the same stuf three times. But it is a must!
Rotating the camera is a good idea to implement, I'll see what I can do with that!

**Comment by etra0** [comment]
I made some progress cleaning the code, and now you can move up/down with the camera with Control and Space.
I'll close this issue when I manage to implement the camera rotation

**Comment by curagea** [comment]
Hello again! The up/down movement is working great. Can't wait to see camera rotation.

How mappable are the camera controls? I've noticed there's now controller support for some of the controls but not all.

**Comment by etra0** [comment]
I don't think buttons will be ever mappables, but I'll make sure all options are available for keyboard or controller.
